// Google place types (Places API (New), Table A, fetched 2026-10-07), minus administrative,
// geographic and trade-service types nobody walks to. Used to suggest exact type matches for
// custom categories, which then use Nearby Search instead of looser Text Search.
// Each entry: [type, label].
export const PLACE_TYPES: readonly (readonly [string, string])[] = [
  ['car_dealer', "Car dealer"],
  ['car_rental', "Car rental"],
  ['car_repair', "Car repair"],
  ['car_wash', "Car wash"],
  ['ebike_charging_station', "Ebike charging station"],
  ['electric_vehicle_charging_station', "Electric vehicle charging station"],
  ['gas_station', "Gas station"],
  ['parking', "Parking"],
  ['parking_garage', "Parking garage"],
  ['parking_lot', "Parking lot"],
  ['tire_shop', "Tire shop"],
  ['business_center', "Business center"],
  ['coworking_space', "Coworking space"],
  ['art_gallery', "Art gallery"],
  ['art_museum', "Art museum"],
  ['art_studio', "Art studio"],
  ['auditorium', "Auditorium"],
  ['cultural_landmark', "Cultural landmark"],
  ['fountain', "Fountain"],
  ['historical_place', "Historical place"],
  ['history_museum', "History museum"],
  ['monument', "Monument"],
  ['museum', "Museum"],
  ['performing_arts_theater', "Performing arts theater"],
  ['sculpture', "Sculpture"],
  ['educational_institution', "Educational institution"],
  ['library', "Library"],
  ['preschool', "Preschool"],
  ['primary_school', "Primary school"],
  ['school', "School"],
  ['secondary_school', "Secondary school"],
  ['university', "University"],
  ['adventure_sports_center', "Adventure sports center"],
  ['amphitheatre', "Amphitheatre"],
  ['amusement_center', "Amusement center"],
  ['amusement_park', "Amusement park"],
  ['aquarium', "Aquarium"],
  ['banquet_hall', "Banquet hall"],
  ['barbecue_area', "Barbecue area"],
  ['botanical_garden', "Botanical garden"],
  ['bowling_alley', "Bowling alley"],
  ['casino', "Casino"],
  ['city_park', "City park"],
  ['comedy_club', "Comedy club"],
  ['community_center', "Community center"],
  ['concert_hall', "Concert hall"],
  ['convention_center', "Convention center"],
  ['cultural_center', "Cultural center"],
  ['cycling_park', "Cycling park"],
  ['dance_hall', "Dance hall"],
  ['dog_park', "Dog park"],
  ['event_venue', "Event venue"],
  ['ferris_wheel', "Ferris wheel"],
  ['garden', "Garden"],
  ['go_karting_venue', "Go karting venue"],
  ['hiking_area', "Hiking area"],
  ['historical_landmark', "Historical landmark"],
  ['indoor_playground', "Indoor playground"],
  ['internet_cafe', "Internet cafe"],
  ['karaoke', "Karaoke"],
  ['live_music_venue', "Live music venue"],
  ['marina', "Marina"],
  ['miniature_golf_course', "Miniature golf course"],
  ['movie_rental', "Movie rental"],
  ['movie_theater', "Movie theater"],
  ['night_club', "Night club"],
  ['observation_deck', "Observation deck"],
  ['opera_house', "Opera house"],
  ['paintball_center', "Paintball center"],
  ['park', "Park"],
  ['philharmonic_hall', "Philharmonic hall"],
  ['picnic_ground', "Picnic ground"],
  ['planetarium', "Planetarium"],
  ['plaza', "Plaza"],
  ['roller_coaster', "Roller coaster"],
  ['skateboard_park', "Skateboard park"],
  ['tourist_attraction', "Tourist attraction"],
  ['video_arcade', "Video arcade"],
  ['vineyard', "Vineyard"],
  ['visitor_center', "Visitor center"],
  ['water_park', "Water park"],
  ['wedding_venue', "Wedding venue"],
  ['wildlife_park', "Wildlife park"],
  ['zoo', "Zoo"],
  ['public_bath', "Public bath"],
  ['public_bathroom', "Public bathroom"],
  ['stable', "Stable"],
  ['atm', "ATM"],
  ['bank', "Bank"],
  ['acai_shop', "Acai shop"],
  ['afghani_restaurant', "Afghani restaurant"],
  ['african_restaurant', "African restaurant"],
  ['american_restaurant', "American restaurant"],
  ['argentinian_restaurant', "Argentinian restaurant"],
  ['asian_fusion_restaurant', "Asian fusion restaurant"],
  ['asian_restaurant', "Asian restaurant"],
  ['australian_restaurant', "Australian restaurant"],
  ['austrian_restaurant', "Austrian restaurant"],
  ['bagel_shop', "Bagel shop"],
  ['bakery', "Bakery"],
  ['bangladeshi_restaurant', "Bangladeshi restaurant"],
  ['bar', "Bar"],
  ['bar_and_grill', "Bar and grill"],
  ['barbecue_restaurant', "Barbecue restaurant"],
  ['basque_restaurant', "Basque restaurant"],
  ['bavarian_restaurant', "Bavarian restaurant"],
  ['beer_garden', "Beer garden"],
  ['belgian_restaurant', "Belgian restaurant"],
  ['bistro', "Bistro"],
  ['brazilian_restaurant', "Brazilian restaurant"],
  ['breakfast_restaurant', "Breakfast restaurant"],
  ['brewery', "Brewery"],
  ['brewpub', "Brewpub"],
  ['british_restaurant', "British restaurant"],
  ['brunch_restaurant', "Brunch restaurant"],
  ['buffet_restaurant', "Buffet restaurant"],
  ['burmese_restaurant', "Burmese restaurant"],
  ['burrito_restaurant', "Burrito restaurant"],
  ['cafe', "Cafe"],
  ['cafeteria', "Cafeteria"],
  ['cajun_restaurant', "Cajun restaurant"],
  ['cake_shop', "Cake shop"],
  ['californian_restaurant', "Californian restaurant"],
  ['cambodian_restaurant', "Cambodian restaurant"],
  ['candy_store', "Candy store"],
  ['cantonese_restaurant', "Cantonese restaurant"],
  ['caribbean_restaurant', "Caribbean restaurant"],
  ['cat_cafe', "Cat cafe"],
  ['chicken_restaurant', "Chicken restaurant"],
  ['chicken_wings_restaurant', "Chicken wings restaurant"],
  ['chilean_restaurant', "Chilean restaurant"],
  ['chinese_noodle_restaurant', "Chinese noodle restaurant"],
  ['chinese_restaurant', "Chinese restaurant"],
  ['chocolate_shop', "Chocolate shop"],
  ['cocktail_bar', "Cocktail bar"],
  ['coffee_roastery', "Coffee roastery"],
  ['coffee_shop', "Coffee shop"],
  ['coffee_stand', "Coffee stand"],
  ['colombian_restaurant', "Colombian restaurant"],
  ['confectionery', "Confectionery"],
  ['croatian_restaurant', "Croatian restaurant"],
  ['cuban_restaurant', "Cuban restaurant"],
  ['czech_restaurant', "Czech restaurant"],
  ['danish_restaurant', "Danish restaurant"],
  ['deli', "Deli"],
  ['dessert_restaurant', "Dessert restaurant"],
  ['dessert_shop', "Dessert shop"],
  ['dim_sum_restaurant', "Dim sum restaurant"],
  ['diner', "Diner"],
  ['dog_cafe', "Dog cafe"],
  ['donut_shop', "Donut shop"],
  ['dumpling_restaurant', "Dumpling restaurant"],
  ['dutch_restaurant', "Dutch restaurant"],
  ['eastern_european_restaurant', "Eastern european restaurant"],
  ['ethiopian_restaurant', "Ethiopian restaurant"],
  ['european_restaurant', "European restaurant"],
  ['falafel_restaurant', "Falafel restaurant"],
  ['family_restaurant', "Family restaurant"],
  ['fast_food_restaurant', "Fast food restaurant"],
  ['filipino_restaurant', "Filipino restaurant"],
  ['fine_dining_restaurant', "Fine dining restaurant"],
  ['fish_and_chips_restaurant', "Fish and chips restaurant"],
  ['fondue_restaurant', "Fondue restaurant"],
  ['food_court', "Food court"],
  ['french_restaurant', "French restaurant"],
  ['fusion_restaurant', "Fusion restaurant"],
  ['gastropub', "Gastropub"],
  ['german_restaurant', "German restaurant"],
  ['greek_restaurant', "Greek restaurant"],
  ['gyro_restaurant', "Gyro restaurant"],
  ['halal_restaurant', "Halal restaurant"],
  ['hamburger_restaurant', "Hamburger restaurant"],
  ['hawaiian_restaurant', "Hawaiian restaurant"],
  ['hookah_bar', "Hookah bar"],
  ['hot_dog_restaurant', "Hot dog restaurant"],
  ['hot_dog_stand', "Hot dog stand"],
  ['hot_pot_restaurant', "Hot pot restaurant"],
  ['hungarian_restaurant', "Hungarian restaurant"],
  ['ice_cream_shop', "Ice cream shop"],
  ['indian_restaurant', "Indian restaurant"],
  ['indonesian_restaurant', "Indonesian restaurant"],
  ['irish_pub', "Irish pub"],
  ['irish_restaurant', "Irish restaurant"],
  ['israeli_restaurant', "Israeli restaurant"],
  ['italian_restaurant', "Italian restaurant"],
  ['japanese_curry_restaurant', "Japanese curry restaurant"],
  ['japanese_izakaya_restaurant', "Japanese izakaya restaurant"],
  ['japanese_restaurant', "Japanese restaurant"],
  ['juice_shop', "Juice shop"],
  ['kebab_shop', "Kebab shop"],
  ['korean_barbecue_restaurant', "Korean barbecue restaurant"],
  ['korean_restaurant', "Korean restaurant"],
  ['latin_american_restaurant', "Latin american restaurant"],
  ['lebanese_restaurant', "Lebanese restaurant"],
  ['lounge_bar', "Lounge bar"],
  ['malaysian_restaurant', "Malaysian restaurant"],
  ['meal_takeaway', "Meal takeaway"],
  ['mediterranean_restaurant', "Mediterranean restaurant"],
  ['mexican_restaurant', "Mexican restaurant"],
  ['middle_eastern_restaurant', "Middle eastern restaurant"],
  ['mongolian_barbecue_restaurant', "Mongolian barbecue restaurant"],
  ['moroccan_restaurant', "Moroccan restaurant"],
  ['noodle_shop', "Noodle shop"],
  ['north_indian_restaurant', "North indian restaurant"],
  ['oyster_bar_restaurant', "Oyster bar restaurant"],
  ['pakistani_restaurant', "Pakistani restaurant"],
  ['pastry_shop', "Pastry shop"],
  ['persian_restaurant', "Persian restaurant"],
  ['peruvian_restaurant', "Peruvian restaurant"],
  ['pizza_restaurant', "Pizza restaurant"],
  ['polish_restaurant', "Polish restaurant"],
  ['portuguese_restaurant', "Portuguese restaurant"],
  ['pub', "Pub"],
  ['ramen_restaurant', "Ramen restaurant"],
  ['restaurant', "Restaurant"],
  ['romanian_restaurant', "Romanian restaurant"],
  ['russian_restaurant', "Russian restaurant"],
  ['salad_shop', "Salad shop"],
  ['sandwich_shop', "Sandwich shop"],
  ['scandinavian_restaurant', "Scandinavian restaurant"],
  ['seafood_restaurant', "Seafood restaurant"],
  ['shawarma_restaurant', "Shawarma restaurant"],
  ['snack_bar', "Snack bar"],
  ['soul_food_restaurant', "Soul food restaurant"],
  ['soup_restaurant', "Soup restaurant"],
  ['south_american_restaurant', "South american restaurant"],
  ['south_indian_restaurant', "South indian restaurant"],
  ['southwestern_us_restaurant', "Southwestern US restaurant"],
  ['spanish_restaurant', "Spanish restaurant"],
  ['sports_bar', "Sports bar"],
  ['sri_lankan_restaurant', "Sri lankan restaurant"],
  ['steak_house', "Steak house"],
  ['sushi_restaurant', "Sushi restaurant"],
  ['swiss_restaurant', "Swiss restaurant"],
  ['taco_restaurant', "Taco restaurant"],
  ['taiwanese_restaurant', "Taiwanese restaurant"],
  ['tapas_restaurant', "Tapas restaurant"],
  ['tea_house', "Tea house"],
  ['tex_mex_restaurant', "Tex mex restaurant"],
  ['thai_restaurant', "Thai restaurant"],
  ['tibetan_restaurant', "Tibetan restaurant"],
  ['tonkatsu_restaurant', "Tonkatsu restaurant"],
  ['turkish_restaurant', "Turkish restaurant"],
  ['ukrainian_restaurant', "Ukrainian restaurant"],
  ['vegan_restaurant', "Vegan restaurant"],
  ['vegetarian_restaurant', "Vegetarian restaurant"],
  ['vietnamese_restaurant', "Vietnamese restaurant"],
  ['western_restaurant', "Western restaurant"],
  ['wine_bar', "Wine bar"],
  ['winery', "Winery"],
  ['yakiniku_restaurant', "Yakiniku restaurant"],
  ['yakitori_restaurant', "Yakitori restaurant"],
  ['fire_station', "Fire station"],
  ['neighborhood_police_station', "Neighborhood police station"],
  ['police', "Police"],
  ['post_office', "Post office"],
  ['chiropractor', "Chiropractor"],
  ['dental_clinic', "Dental clinic"],
  ['dentist', "Dentist"],
  ['doctor', "Doctor"],
  ['drugstore', "Drugstore"],
  ['general_hospital', "General hospital"],
  ['hospital', "Hospital"],
  ['massage', "Massage"],
  ['massage_spa', "Massage spa"],
  ['medical_center', "Medical center"],
  ['medical_clinic', "Medical clinic"],
  ['medical_lab', "Medical lab"],
  ['pharmacy', "Pharmacy"],
  ['physiotherapist', "Physiotherapist"],
  ['sauna', "Sauna"],
  ['skin_care_clinic', "Skin care clinic"],
  ['spa', "Spa"],
  ['tanning_studio', "Tanning studio"],
  ['wellness_center', "Wellness center"],
  ['yoga_studio', "Yoga studio"],
  ['bed_and_breakfast', "Bed and breakfast"],
  ['cottage', "Cottage"],
  ['guest_house', "Guest house"],
  ['hostel', "Hostel"],
  ['hotel', "Hotel"],
  ['inn', "Inn"],
  ['lodging', "Lodging"],
  ['motel', "Motel"],
  ['nature_preserve', "Nature preserve"],
  ['buddhist_temple', "Buddhist temple"],
  ['church', "Church"],
  ['hindu_temple', "Hindu temple"],
  ['mosque', "Mosque"],
  ['shinto_shrine', "Shinto shrine"],
  ['synagogue', "Synagogue"],
  ['barber_shop', "Barber shop"],
  ['beautician', "Beautician"],
  ['beauty_salon', "Beauty salon"],
  ['body_art_service', "Body art service"],
  ['child_care_agency', "Child care agency"],
  ['florist', "Florist"],
  ['foot_care', "Foot care"],
  ['hair_care', "Hair care"],
  ['hair_salon', "Hair salon"],
  ['laundry', "Laundry"],
  ['makeup_artist', "Makeup artist"],
  ['nail_salon', "Nail salon"],
  ['pet_boarding_service', "Pet boarding service"],
  ['pet_care', "Pet care"],
  ['shipping_service', "Shipping service"],
  ['storage', "Storage"],
  ['tailor', "Tailor"],
  ['tourist_information_center', "Tourist information center"],
  ['veterinary_care', "Veterinary care"],
  ['asian_grocery_store', "Asian grocery store"],
  ['auto_parts_store', "Auto parts store"],
  ['bicycle_store', "Bicycle store"],
  ['book_store', "Book store"],
  ['building_materials_store', "Building materials store"],
  ['butcher_shop', "Butcher shop"],
  ['cell_phone_store', "Cell phone store"],
  ['clothing_store', "Clothing store"],
  ['convenience_store', "Convenience store"],
  ['cosmetics_store', "Cosmetics store"],
  ['department_store', "Department store"],
  ['discount_store', "Discount store"],
  ['discount_supermarket', "Discount supermarket"],
  ['electronics_store', "Electronics store"],
  ['farmers_market', "Farmers market"],
  ['flea_market', "Flea market"],
  ['furniture_store', "Furniture store"],
  ['garden_center', "Garden center"],
  ['general_store', "General store"],
  ['gift_shop', "Gift shop"],
  ['grocery_store', "Grocery store"],
  ['hardware_store', "Hardware store"],
  ['health_food_store', "Health food store"],
  ['home_goods_store', "Home goods store"],
  ['home_improvement_store', "Home improvement store"],
  ['hypermarket', "Hypermarket"],
  ['jewelry_store', "Jewelry store"],
  ['liquor_store', "Liquor store"],
  ['market', "Market"],
  ['pet_store', "Pet store"],
  ['shoe_store', "Shoe store"],
  ['shopping_mall', "Shopping mall"],
  ['sporting_goods_store', "Sporting goods store"],
  ['sportswear_store', "Sportswear store"],
  ['supermarket', "Supermarket"],
  ['tea_store', "Tea store"],
  ['thrift_store', "Thrift store"],
  ['toy_store', "Toy store"],
  ['womens_clothing_store', "Women's clothing store"],
  ['arena', "Arena"],
  ['athletic_field', "Athletic field"],
  ['fishing_pier', "Fishing pier"],
  ['fitness_center', "Fitness center"],
  ['golf_course', "Golf course"],
  ['gym', "Gym"],
  ['ice_skating_rink', "Ice skating rink"],
  ['indoor_golf_course', "Indoor golf course"],
  ['playground', "Playground"],
  ['sports_activity_location', "Sports activity location"],
  ['sports_club', "Sports club"],
  ['sports_coaching', "Sports coaching"],
  ['sports_complex', "Sports complex"],
  ['sports_school', "Sports school"],
  ['stadium', "Stadium"],
  ['swimming_pool', "Swimming pool"],
  ['tennis_court', "Tennis court"],
  ['bike_sharing_station', "Bike sharing station"],
  ['bridge', "Bridge"],
  ['bus_station', "Bus station"],
  ['bus_stop', "Bus stop"],
  ['ferry_service', "Ferry service"],
  ['ferry_terminal', "Ferry terminal"],
  ['light_rail_station', "Light rail station"],
  ['park_and_ride', "Park and ride"],
  ['subway_station', "Subway station"],
  ['taxi_service', "Taxi service"],
  ['taxi_stand', "Taxi stand"],
  ['train_station', "Train station"],
  ['train_ticket_office', "Train ticket office"],
  ['tram_stop', "Tram stop"],
  ['transit_depot', "Transit depot"],
  ['transit_station', "Transit station"],
  ['transit_stop', "Transit stop"],
];
